version: 2
jobs:
  build:
    docker:
    - image: gettyio/maven
    working_directory: /tmp/repo
    steps:
    - checkout

    - run: mvn package -Dmaven.test.skip=true

    # tries to persist distribution libs to workspace
    - persist_to_workspace:
        root: /tmp/repo
        paths:
        - target

  test:
    docker:
    - image: gettyio/maven
    working_directory: /tmp/repo
    steps:
    - checkout

    # tries to restore distribution libs from workspace
    - attach_workspace:
        at: /tmp/repo
    
    - run: mvn test

  docker-build-push:
    docker:
    - image: docker:stable
      environment:
        DIST_VERSION: 1.0.0

    working_directory: /tmp/repo

    steps:
    - run: apk add --no-cache git

    - checkout

    - setup_remote_docker

    # tries to restore distribution libs from workspace
    - attach_workspace:
        at: /tmp/repo

    # logs in to docker hub then
    # build and push image to docker hub
    - run: |
        docker login -u $DOCKER_LOGIN -p $DOCKER_PWD > /dev/null 2>&1
        docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
        if [ "${CIRCLE_BRANCH}" == "master" ]; then
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$DIST_VERISON
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$DIST_VERISON
        else
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$DIST_VERISON-$CIRCLE_BRANCH
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$DIST_VERISON-$CIRCLE_BRANCH
        fi

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - test:
        requires:
        - build
    - docker-build-push:
        context: docker-hub-credentials
        requires:
        - test
        filters:
          branches:
            only:
            - develop
            - master
